version: "3.8"
services:
  api:
    container_name: api-container
    build: ./back-end
    ports:
      - "4000:4000"

  client:
    container_name: client-container
    build: ./front-end
    ports:
      - "3000:3000"

    tty: true
    depends_on:
      - api
